services:
  - type: web
    name: tib-cat
    env: node
    plan: starter
    repo: https://github.com/OpenPecha/tib-cat.git
    branch: main
    buildCommand: npm ci --production=false && npm run build && npm prune --production
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: ~18.18.0
      - key: NODE_ENV
        value: production